### ISSUE TITLE
Please add git to 4.0

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/docker-python-base#210]
Currently the 4.0 image does not include git

**Comment by hillairet** [comment]
Just out of curiosity, what do you need git for?

**Comment by qw-in** [comment]
It was a build dependency for something I tried to install

**Comment by hillairet** [comment]
That seems to be an edge case. I'll see for 4.1 how much this increases the image size.

**Comment by hillairet** [comment]
Not clear exactly why we need git so I'll close
