### ISSUE TITLE
Please add gcc to 4.0 image

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/docker-python-base#211]
Lots of packages require it as a build dep

**Comment by hillairet** [comment]
Wait is it still true with slim base image instead of alpine???
Packages should be wheel packages and therefore [should not require compilcation](https://realpython.com/python-wheels/#advantages-of-python-wheels).
I'm gonna hold off on this.

**Comment by hillairet** [comment]
I'll assume this is not needed and close
