### ISSUE TITLE
mkdir: cannot create directory '/reports': Permission denied

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/docker-python-base#275]
Issues with the most recent push #270 because of root permissions. This should be an easy fix from `/reports` to `/python/reports` because the docker user is `python` which doesn't have permission to create on the root.

@hillairet is this an okay solution?

**Comment by hillairet** [comment]
Oh yeah totally!!!
I am out of it cause `/python/reports` makes more sense. My bad!

We should setup a build of the image though using github actions!

**Comment by Nathan-Nesbitt** [comment]
That would be great!
