### ISSUE TITLE
Improved versioning

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/docker-python-base#279]
So far the versioning has been pretty standard with a major release number change for significant changes to the structure of the image and a minor release number change for upgrades.

This is not working well because we have to maintain older python versions too. We ran into a situation where we have an app that cannot use python 3.10 so we need to have 4.2.1 which is not a bug fix but will have many changes from `main` except with the python version 3.9.6 and requirements from version 4.2.

Instead we should have a version with the year/month and the python version such as `2021.11-python3.10.0` this way the user knows when the packages were updated and we can have multiple python version maintained in parallel.

We should start with the January release.

**Comment by jsemearns** [comment]
Can't we checkout from the tag that we want to update e.g `git checkout <tag_version>`, branch off from there and create a release based on that branch after making changes?

This won't be semantic enough though compared to the suggestion above where we specify the python version and given that it will most likely only be used by Satel, will benefit us more.. Then again, we could also specify in the docs (README or docker hub) what python version is being used by a certain release.

**Comment by hillairet** [comment]
@jsemearns That's what we are doing and it's not pretty:
We need 4.2 right now which is python 3.9.6 and we need it for one of our projects. We may need it for a while and maybe even want to upgrade the packages leading to 4.2.X which are patch versions, as in bug fixes, not upgrade of packages. While on the main branch we'd go from 4.3 to 4.4 when upgrading the packages. That's messy.

The version number should tell you what you need to know as a user that's why I propose date so one knows how "fresh" the packages in it are, and the python version depending what we may need.
Now we could have semantic + python version like the [python image](https://hub.docker.com/_/python/?tab=description).
See how it has the python version AND the alpine version in the tags?
* 3.10.0-alpine3.14
* 3.10.0-alpine3.15

I just think for our use case, date is simpler and more meaningful

**Comment by qw-in** [comment]
Good idea, this has been a pain point for me in the past. I like the date idea too - could even consider syncing it to Shopify's api release

**Comment by hillairet** [comment]
The release will be part of our quarterly maintenance so yeah it will be effectively in sync!
