### ISSUE TITLE
flake8-isort disagrees with black 

### ISSUE THREAD

**Issue by estellajaysong** [SatelCreative/docker-python-base#305]
When I run `validatecodeonce` I got a ton of errors like below in `CHECK LINTING `stage:
```
./base_models/__init__.py:1:1: I001 isort found an import in the wrong position
./base_models/__init__.py:2:1: I001 isort found an import in the wrong position
./base_models/__init__.py:3:1: I001 isort found an import in the wrong position
./base_models/__init__.py:4:1: I001 isort found an import in the wrong position
./base_models/__init__.py:5:1: I001 isort found an import in the wrong position
./base_models/__init__.py:6:1: I001 isort found an import in the wrong position
```
If I run `isort .`, the `CHECK LINTING` errors go away but `CHECK FORMATTING` fails.
But if I run `black` or `isort --profile black`, the `CHECK FORMATTING` errors go away but the `CHECK LINTING` errors return.

**Comment by hillairet** [comment]
@estellajaysong It would help a lot to have the docker-python-base version and the configurations you are using for flake8 and isort ...

**Comment by estellajaysong** [comment]
Fixed with isort config
